# Generated by Django 5.1.5 on 2025-02-27 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=400)),
                ('type_p', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='img')),
            ],
        ),
    ]
