# Generated by Django 5.1.5 on 2025-02-27 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0003_typeofpoint_alter_point_type_p'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityOfPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='point',
            name='city',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='points.cityofpoint'),
        ),
    ]
