# Generated by Django 5.1.5 on 2025-02-27 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0004_cityofpoint_point_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='image',
            field=models.ImageField(upload_to='static/img'),
        ),
    ]
