# Generated by Django 5.1.5 on 2025-03-05 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0005_alter_point_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='image',
            field=models.ImageField(upload_to='img'),
        ),
    ]
